// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAssignee(arg1:number,arg2:number):Promise<void>;

export function AddComment(arg1:number,arg2:number,arg3:string):Promise<models.TaskComment>;

export function AddDependency(arg1:number,arg2:number):Promise<void>;

export function AddTaskLabel(arg1:number,arg2:number):Promise<void>;

export function CreateBoard(arg1:string,arg2:number,arg3:boolean):Promise<models.BoardWithColumns>;

export function CreateCategory(arg1:models.Category):Promise<number>;

export function CreateColumn(arg1:number,arg2:string,arg3:string,arg4:any):Promise<models.KanbanColumn>;

export function CreateEvent(arg1:models.Event):Promise<number>;

export function CreateLabel(arg1:number,arg2:string,arg3:string):Promise<models.Label>;

export function CreateNote(arg1:models.Note):Promise<number>;

export function CreateProfile(arg1:models.CreateProfileInput):Promise<models.ProfileSummary>;

export function CreateSubtask(arg1:number,arg2:string):Promise<models.Subtask>;

export function CreateTask(arg1:models.Task):Promise<number>;

export function DeleteBoard(arg1:number):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteColumn(arg1:number):Promise<void>;

export function DeleteComment(arg1:number):Promise<void>;

export function DeleteEvent(arg1:number):Promise<void>;

export function DeleteFromCalendar(arg1:number,arg2:string):Promise<void>;

export function DeleteLabel(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DeleteSubtask(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function DisconnectGoogleCalendar(arg1:number):Promise<void>;

export function GetActivity(arg1:number):Promise<Array<models.TaskActivity>>;

export function GetAllCategories():Promise<Array<models.Category>>;

export function GetAllEvents():Promise<Array<models.Event>>;

export function GetAllNotes():Promise<Array<models.Note>>;

export function GetAllProfiles():Promise<Array<models.ProfileSummary>>;

export function GetAllTasks():Promise<Array<models.Task>>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetBoardWithColumns(arg1:number):Promise<models.BoardWithColumns>;

export function GetBoardsByProfile(arg1:number,arg2:string):Promise<Array<models.BoardWithColumns>>;

export function GetCategoryByID(arg1:number):Promise<models.Category>;

export function GetCompletedTasks():Promise<Array<models.Task>>;

export function GetCurrentProfileID():Promise<number>;

export function GetEventByID(arg1:number):Promise<models.Event>;

export function GetFavoriteNotes():Promise<Array<models.Note>>;

export function GetLabelsByBoard(arg1:number):Promise<Array<models.Label>>;

export function GetNoteByID(arg1:number):Promise<models.Note>;

export function GetNoteCategories():Promise<Array<models.Category>>;

export function GetPendingTasks():Promise<Array<models.Task>>;

export function GetProfileByID(arg1:number):Promise<models.ProfileSummary>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTaskByID(arg1:number):Promise<models.Task>;

export function GetTaskCategories():Promise<Array<models.Category>>;

export function GetTaskDetail(arg1:number):Promise<models.TaskDetail>;

export function GetTasksByBoard(arg1:number):Promise<Array<models.Task>>;

export function GetTasksByColumn(arg1:number):Promise<Array<models.Task>>;

export function GetTasksByFilter(arg1:models.TaskFilter):Promise<Array<models.Task>>;

export function GetTodayEvents():Promise<Array<models.Event>>;

export function GetUpcomingEvents():Promise<Array<models.Event>>;

export function GoogleCalendarConfigured():Promise<boolean>;

export function GoogleCalendarConnected(arg1:number):Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function HasAnyProfile():Promise<boolean>;

export function MoveTask(arg1:number,arg2:number,arg3:number):Promise<void>;

export function RemoveAssignee(arg1:number,arg2:number):Promise<void>;

export function RemoveDependency(arg1:number,arg2:number):Promise<void>;

export function RemoveTaskLabel(arg1:number,arg2:number):Promise<void>;

export function ReorderColumns(arg1:Array<number>):Promise<void>;

export function SearchNotes(arg1:string):Promise<Array<models.Note>>;

export function SetCurrentProfile(arg1:number):Promise<void>;

export function SetPin(arg1:number,arg2:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartGoogleAuth(arg1:number):Promise<void>;

export function SyncEventToCalendar(arg1:number,arg2:number):Promise<void>;

export function SyncTaskToCalendar(arg1:number,arg2:number):Promise<void>;

export function ToggleNoteFavorite(arg1:number):Promise<void>;

export function ToggleSubtask(arg1:number):Promise<void>;

export function ToggleTaskStatus(arg1:number):Promise<void>;

export function UpdateBoard(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function UpdateCategory(arg1:models.Category):Promise<void>;

export function UpdateColumn(arg1:number,arg2:string,arg3:string,arg4:any):Promise<void>;

export function UpdateEvent(arg1:models.Event):Promise<void>;

export function UpdateNote(arg1:models.Note):Promise<void>;

export function UpdateProfile(arg1:number,arg2:models.CreateProfileInput):Promise<void>;

export function UpdateProgress(arg1:number,arg2:number):Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<void>;

export function VerifyPin(arg1:number,arg2:string):Promise<boolean>;

export function ConnectWhatsApp():Promise<void>;

export function DeleteWAScheduled(arg1:number):Promise<void>;

export function DisconnectWhatsApp():Promise<void>;

export function GetWAChats():Promise<Array<models.WAChat>>;

export function GetWAMessages(arg1:string,arg2:number):Promise<Array<models.WAMessage>>;

export function GetWAScheduled():Promise<Array<models.WAScheduled>>;

export function GetWhatsAppStatus():Promise<models.WAStatusInfo>;

export function LogoutWhatsApp():Promise<void>;

export function MarkWARead(arg1:string):Promise<void>;

export function ScheduleWAMessage(arg1:models.WAScheduleInput):Promise<void>;

export function SendWAMessage(arg1:string,arg2:string):Promise<void>;
