// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAssignee(arg1, arg2) {
  return window['go']['main']['App']['AddAssignee'](arg1, arg2);
}

export function AddComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddComment'](arg1, arg2, arg3);
}

export function AddDependency(arg1, arg2) {
  return window['go']['main']['App']['AddDependency'](arg1, arg2);
}

export function AddTaskLabel(arg1, arg2) {
  return window['go']['main']['App']['AddTaskLabel'](arg1, arg2);
}

export function CreateBoard(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBoard'](arg1, arg2, arg3);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateColumn'](arg1, arg2, arg3, arg4);
}

export function CreateEvent(arg1) {
  return window['go']['main']['App']['CreateEvent'](arg1);
}

export function CreateLabel(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLabel'](arg1, arg2, arg3);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateSubtask(arg1, arg2) {
  return window['go']['main']['App']['CreateSubtask'](arg1, arg2);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteBoard(arg1) {
  return window['go']['main']['App']['DeleteBoard'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteColumn(arg1) {
  return window['go']['main']['App']['DeleteColumn'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['App']['DeleteComment'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteFromCalendar(arg1, arg2) {
  return window['go']['main']['App']['DeleteFromCalendar'](arg1, arg2);
}

export function DeleteLabel(arg1) {
  return window['go']['main']['App']['DeleteLabel'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSubtask(arg1) {
  return window['go']['main']['App']['DeleteSubtask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DisconnectGoogleCalendar(arg1) {
  return window['go']['main']['App']['DisconnectGoogleCalendar'](arg1);
}

export function GetActivity(arg1) {
  return window['go']['main']['App']['GetActivity'](arg1);
}

export function GetAllCategories() {
  return window['go']['main']['App']['GetAllCategories']();
}

export function GetAllEvents() {
  return window['go']['main']['App']['GetAllEvents']();
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetAllProfiles() {
  return window['go']['main']['App']['GetAllProfiles']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBoardWithColumns(arg1) {
  return window['go']['main']['App']['GetBoardWithColumns'](arg1);
}

export function GetBoardsByProfile(arg1, arg2) {
  return window['go']['main']['App']['GetBoardsByProfile'](arg1, arg2);
}

export function GetCategoryByID(arg1) {
  return window['go']['main']['App']['GetCategoryByID'](arg1);
}

export function GetCompletedTasks() {
  return window['go']['main']['App']['GetCompletedTasks']();
}

export function GetCurrentProfileID() {
  return window['go']['main']['App']['GetCurrentProfileID']();
}

export function GetEventByID(arg1) {
  return window['go']['main']['App']['GetEventByID'](arg1);
}

export function GetFavoriteNotes() {
  return window['go']['main']['App']['GetFavoriteNotes']();
}

export function GetLabelsByBoard(arg1) {
  return window['go']['main']['App']['GetLabelsByBoard'](arg1);
}

export function GetNoteByID(arg1) {
  return window['go']['main']['App']['GetNoteByID'](arg1);
}

export function GetNoteCategories() {
  return window['go']['main']['App']['GetNoteCategories']();
}

export function GetPendingTasks() {
  return window['go']['main']['App']['GetPendingTasks']();
}

export function GetProfileByID(arg1) {
  return window['go']['main']['App']['GetProfileByID'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetTaskByID(arg1) {
  return window['go']['main']['App']['GetTaskByID'](arg1);
}

export function GetTaskCategories() {
  return window['go']['main']['App']['GetTaskCategories']();
}

export function GetTaskDetail(arg1) {
  return window['go']['main']['App']['GetTaskDetail'](arg1);
}

export function GetTasksByBoard(arg1) {
  return window['go']['main']['App']['GetTasksByBoard'](arg1);
}

export function GetTasksByColumn(arg1) {
  return window['go']['main']['App']['GetTasksByColumn'](arg1);
}

export function GetTasksByFilter(arg1) {
  return window['go']['main']['App']['GetTasksByFilter'](arg1);
}

export function GetTodayEvents() {
  return window['go']['main']['App']['GetTodayEvents']();
}

export function GetUpcomingEvents() {
  return window['go']['main']['App']['GetUpcomingEvents']();
}

export function GoogleCalendarConfigured() {
  return window['go']['main']['App']['GoogleCalendarConfigured']();
}

export function GoogleCalendarConnected(arg1) {
  return window['go']['main']['App']['GoogleCalendarConnected'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasAnyProfile() {
  return window['go']['main']['App']['HasAnyProfile']();
}

export function MoveTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2, arg3);
}

export function RemoveAssignee(arg1, arg2) {
  return window['go']['main']['App']['RemoveAssignee'](arg1, arg2);
}

export function RemoveDependency(arg1, arg2) {
  return window['go']['main']['App']['RemoveDependency'](arg1, arg2);
}

export function RemoveTaskLabel(arg1, arg2) {
  return window['go']['main']['App']['RemoveTaskLabel'](arg1, arg2);
}

export function ReorderColumns(arg1) {
  return window['go']['main']['App']['ReorderColumns'](arg1);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}

export function SetCurrentProfile(arg1) {
  return window['go']['main']['App']['SetCurrentProfile'](arg1);
}

export function SetPin(arg1, arg2) {
  return window['go']['main']['App']['SetPin'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartGoogleAuth(arg1) {
  return window['go']['main']['App']['StartGoogleAuth'](arg1);
}

export function SyncEventToCalendar(arg1, arg2) {
  return window['go']['main']['App']['SyncEventToCalendar'](arg1, arg2);
}

export function SyncTaskToCalendar(arg1, arg2) {
  return window['go']['main']['App']['SyncTaskToCalendar'](arg1, arg2);
}

export function ToggleNoteFavorite(arg1) {
  return window['go']['main']['App']['ToggleNoteFavorite'](arg1);
}

export function ToggleSubtask(arg1) {
  return window['go']['main']['App']['ToggleSubtask'](arg1);
}

export function ToggleTaskStatus(arg1) {
  return window['go']['main']['App']['ToggleTaskStatus'](arg1);
}

export function UpdateBoard(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateBoard'](arg1, arg2, arg3);
}

export function UpdateCategory(arg1) {
  return window['go']['main']['App']['UpdateCategory'](arg1);
}

export function UpdateColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateColumn'](arg1, arg2, arg3, arg4);
}

export function UpdateEvent(arg1) {
  return window['go']['main']['App']['UpdateEvent'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function UpdateProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateProgress'](arg1, arg2);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function VerifyPin(arg1, arg2) {
  return window['go']['main']['App']['VerifyPin'](arg1, arg2);
}
