// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateEvent(arg1) {
  return window['go']['main']['App']['CreateEvent'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAllCategories() {
  return window['go']['main']['App']['GetAllCategories']();
}

export function GetAllEvents() {
  return window['go']['main']['App']['GetAllEvents']();
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCategoryByID(arg1) {
  return window['go']['main']['App']['GetCategoryByID'](arg1);
}

export function GetCompletedTasks() {
  return window['go']['main']['App']['GetCompletedTasks']();
}

export function GetEventByID(arg1) {
  return window['go']['main']['App']['GetEventByID'](arg1);
}

export function GetFavoriteNotes() {
  return window['go']['main']['App']['GetFavoriteNotes']();
}

export function GetNoteByID(arg1) {
  return window['go']['main']['App']['GetNoteByID'](arg1);
}

export function GetNoteCategories() {
  return window['go']['main']['App']['GetNoteCategories']();
}

export function GetPendingTasks() {
  return window['go']['main']['App']['GetPendingTasks']();
}

export function GetTaskByID(arg1) {
  return window['go']['main']['App']['GetTaskByID'](arg1);
}

export function GetTaskCategories() {
  return window['go']['main']['App']['GetTaskCategories']();
}

export function GetTasksByFilter(arg1) {
  return window['go']['main']['App']['GetTasksByFilter'](arg1);
}

export function GetTodayEvents() {
  return window['go']['main']['App']['GetTodayEvents']();
}

export function GetUpcomingEvents() {
  return window['go']['main']['App']['GetUpcomingEvents']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}

export function ToggleNoteFavorite(arg1) {
  return window['go']['main']['App']['ToggleNoteFavorite'](arg1);
}

export function ToggleTaskStatus(arg1) {
  return window['go']['main']['App']['ToggleTaskStatus'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['main']['App']['UpdateCategory'](arg1);
}

export function UpdateEvent(arg1) {
  return window['go']['main']['App']['UpdateEvent'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
