// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCategory(arg1:models.Category):Promise<number>;

export function CreateEvent(arg1:models.Event):Promise<number>;

export function CreateNote(arg1:models.Note):Promise<number>;

export function CreateTask(arg1:models.Task):Promise<number>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteEvent(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAllCategories():Promise<Array<models.Category>>;

export function GetAllEvents():Promise<Array<models.Event>>;

export function GetAllNotes():Promise<Array<models.Note>>;

export function GetAllTasks():Promise<Array<models.Task>>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetCategoryByID(arg1:number):Promise<models.Category>;

export function GetCompletedTasks():Promise<Array<models.Task>>;

export function GetEventByID(arg1:number):Promise<models.Event>;

export function GetFavoriteNotes():Promise<Array<models.Note>>;

export function GetNoteByID(arg1:number):Promise<models.Note>;

export function GetNoteCategories():Promise<Array<models.Category>>;

export function GetPendingTasks():Promise<Array<models.Task>>;

export function GetTaskByID(arg1:number):Promise<models.Task>;

export function GetTaskCategories():Promise<Array<models.Category>>;

export function GetTasksByFilter(arg1:models.TaskFilter):Promise<Array<models.Task>>;

export function GetTodayEvents():Promise<Array<models.Event>>;

export function GetUpcomingEvents():Promise<Array<models.Event>>;

export function Greet(arg1:string):Promise<string>;

export function SearchNotes(arg1:string):Promise<Array<models.Note>>;

export function SetTheme(arg1:string):Promise<void>;

export function ToggleNoteFavorite(arg1:number):Promise<void>;

export function ToggleTaskStatus(arg1:number):Promise<void>;

export function UpdateCategory(arg1:models.Category):Promise<void>;

export function UpdateEvent(arg1:models.Event):Promise<void>;

export function UpdateNote(arg1:models.Note):Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<void>;
